### PR TITLE
Fix delay for masternode activation/resign delay

### LINKED ISSUE #635: height in GetActivationDelay wrong
https://github.com/DeFiCh/ain/blob/1cdc7e05b8340fbd51ba76a1263a6e1fb194e6cd/src/masternodes/masternodes.cpp#L118-L124

Hi,

please check out the referenced code.
You are taking the ActivationDelay (and ResignDelay) from the current height, not from creationHeight. This can lead to problems when changing the delays in the future.

### PR DESCRIPTION
**Pull request by Mixa84**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
When checking the state of MN, instead of getting the delay from params for current height it will use the height when MN was created/resigned. This way it will keep old delay and new delays set after some height will apply only on MNs create/resigned after that height.

#### Which issue(s) does this PR fixes?:

Close #635

### CODE REVIEW

File: src/masternodes/masternodes.cpp [hunk 1]
```diff
@@ -115,14 +115,16 @@ CMasternode::State CMasternode::GetState(int height) const
 {
     if (resignHeight == -1) { // enabled or pre-enabled
         // Special case for genesis block
-        if (creationHeight == 0 || height >= creationHeight + GetMnActivationDelay(height)) {
-            return State::ENABLED;
+        if (creationHeight == 0 || (height < Params().GetConsensus().EunosPayaHeight && height >= creationHeight + GetMnActivationDelay(height))
```
Comment (prasannavl) [inline src/masternodes/masternodes.cpp:118]: Readability: What do you think about lifting the `Params().GetConsensus().EunosPayaHeight` to a var on the top of the fn?

**Review by prasannavl — APPROVED** [review]
