### PR TITLE
Remove usage of ForEachAccount

### LINKED ISSUE #1763: OCG Voting rewards are not spendable
#### What happened:
voted with onchain governance and got reward on my address but wallet does not show tokenbalance and therefore the DFI are not spendable

#### What you expected to happen:
rewards from onchainvoting are listed in gettokenbalances and are spendable

#### How to reproduce it (as minimally and precisely as possible):
vote for a DFIP/CFP and get a reward. Reward is shown on defiscan but not on local wallet

#### What are your environment parameters:
defichain desktop wallet with latest noderelease

#### Anything else we need to know?:
restore with snapshot did not help and another telegram with multiple masternodes told that only one reward is shown in balance.

### PR DESCRIPTION
**Pull request by shohamc1**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:

Masternode operator addresses receiving voting rewards do not show up on `gettokenbalances`. This PR fixes the issue so that voting rewards show up in `gettokenbalances`.

#### Which issue(s) does this PR fixes?:

Fixes #1763

### CODE REVIEW

File: src/masternodes/rpc_accounts.cpp [hunk 1]
```diff
@@ -549,15 +549,13 @@ UniValue gettokenbalances(const JSONRPCRequest& request) {
...
 
-    mnview.ForEachAccount([&](CScript const & account) {
-        if (IsMineCached(*pwallet, account) == ISMINE_SPENDABLE) {
-            mnview.CalculateOwnerRewards(account, targetHeight);
-            mnview.ForEachBalance([&](CScript const & owner, CTokenAmount balance) {
-                return account == owner && totalBalances.Add(balance);
-            }, {account, DCT_ID{}});
-        }
+    mnview.ForEachBalance([&](CScript const & owner, CTokenAmount balance) {
+        if (IsMineCached(*pwallet, owner))
```
Comment (Bushstar) [inline src/masternodes/rpc_accounts.cpp:553]: Restore cal to CalculateOwnerRewards to return the balance with pool rewards.

**Review by Bushstar — APPROVED** [review]

**Review by prasannavl — APPROVED** [review]

**Comment by prasannavl** [comment]
TODO: Impact metrics
